version: "3.1"

services:
  cloudflared:
    image: cloudflared
    build:
      context: .
      dockerfile: cloudflared.Dockerfile
    restart: on-failure
    depends_on:
      - cocalc-proxy
    volumes:
      - ~/.cloudflared:/etc/cloudflared
  cocalc-proxy:
    image: nginx:latest
    restart: always
    depends_on:
      - cocalc
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  cocalc:
    image: cocalc
    build:
      context: .
      dockerfile: cocalc.Dockerfile
    restart: always
    ports:
      - 127.0.0.1:2222:22
    volumes:
      - data:/projects

volumes:
  data: